version: '2'
services:
    ngocjr7blog-app:
        image: ngocjr7blog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ngocjr7blog-mysql:3306/ngocjr7blog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ngocjr7blog-mysql:
        extends:
            file: mysql.yml
            service: ngocjr7blog-mysql
